DownloadFavorites : true
Blacklist:
  Enabled: true
  Strings:
  - (Live
  - (The Best Of The E.N.D. Version)
  - (as made famous by
  - Karaoke Version
  Artists:
  - The Karaoke Channel
  - Covered Up
  - Immense Media
  - Backing Force
  - The 1999 Players
  - Gynmusic Studios
  - ProSource Karaoke
  - Michael williams
  - Hilmer Rose
  - Andres Espinosa
  - Remix Radio DJ
  - Top 40 Hits
  - Maxence Luchi
  - Stingray
  - De Oln'zelse Köpperbloazers
  - Farbwall
  - License and Registration Players
  - MIDIFine Systems
  - Singer's Best
  - Remixation
  - Backing Track Central
  - Cvdb
  - Pop Anthems Karaoke Players
  - Taryn Torres
  - Chart Collective
  - Mr. Entertainer Karaoke
  - Heaven 11
  - 2000's Karaoke Players
  - The Beat Mechanics
  - Party Tyme
  - No.1s Karaoke Players
  - ProTracks (Karaoke)
  - Karaoke Players
  - Easy Karaoke Players
  - Glitzzi Girlz
  - Grandmix
  - TouchTone Da SoundGawd
  - Pop Star Baby
  - LucasGitanoFamily
  - Infiniti Cuntz
  - CA$hMANE
  - The Rock Heroes
  - BOLD tone
  - Skating With The Stars
  - Party Tyme Karaoke
  - Anna Gramm
  - Best DJ Collection
  - BFM Hits
  - AVID Karaoke
  - LTMJP
  - Wide Open Mouth Karaoke
  - Kids Party Karaoke Players
  - LZ*
  - Tonight's Gonna Be a Good Night
  - Deluxe Session
  - Khs
  - オルゴールサウンド J-POP
